### ISSUE TITLE
Packagist (composer) packaging?

### ISSUE THREAD

**Issue by martonmiklos** [tme-dev/TME-API#5]
Hello guys,
First of all many thanks for putting this together. 

Have you considered to add a composer.json file to be able to publish on packagist and use composer to add it as a dependency?

**Comment by piotrkochan** [comment]
Why not #6

**Comment by piotrkochan** [comment]
repository available at https://github.com/tme-dev/api-client-guzzle
package available as tme/api-client-guzzle in composer
